# Autogenerated wrapper script for DecFP_jll for aarch64-linux-musl
export libbid

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libbid`
const libbid_splitpath = ["lib", "libbid.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libbid_path = ""

# libbid-specific global declaration
# This will be filled out by __init__()
libbid_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libbid = "libbid.so"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"DecFP")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libbid_path = normpath(joinpath(artifact_dir, libbid_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libbid_handle = dlopen(libbid_path)
    push!(LIBPATH_list, dirname(libbid_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')
end  # __init__()

